source "https://rubygems.org"

ruby "1.9.3"
gem "unicorn"
gem "sinatra"
gem "sinatra-support", require: "sinatra/support"
gem "sinatra-assetpack", :require => "sinatra/assetpack"
gem "ruroku"

gem "coffee-script"
gem "compass"
gem "compass-h5bp"
gem "mustache"
gem "httparty"
gem "json"